---
  domain: "zoneminder.xyz.com"
  secret_key: "XXX"
  username: "YYY"
  password_hash: "ZZZ"
  seconds_off: 8
  seconds_on: 8
  frame_width: 1024
  frame_height: 1000
  screenoff_enabled: False
  speed_x: 90
  speed_y: 60